### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by 3DComputing** [jeffbass/yin-yang-ranch#1]
Hi Jeff,  love your project, found it on Adrians site
I look as old as you,  been 20 years in electronics, and about the same in software.  Now doing windows based comms,  web servers, api servers etc.

if you need some help, yell]
github@3d.com.au

**Comment by jeffbass** [comment]
Thanks! My project is still too early in development to benefit from help. But I really appreciate the offer and will definitely send you a note in about 3 months when I'm at a more stable and more complete release. I am going to put up the imagenode repository in the next month, then the imagehub repository after that. The docs and design will be stable enough then to make collaboration easier.

**Comment by jeffbass** [comment]
Thanks again for your offer to help. I really appreciate it. I am closing this issue for now and will re-open it when I have the code further along. When I re-open the issue, you will be pinged by GitHub.

**Comment by jeffbass** [comment]
Hi again. Was away from this project for a bit, but I wanted you to know that I pushed the imagenode and imagehub repositories to GitHub. The whole image capture, transmission and storage pipeline of my project is posted on GitHub now. If you have time and interest, it would be great if you could clone the repos onto your computers and try running the tests using the posted docs. I have only had a couple of folks helping with testing and want to know if this stuff runs OK on other machines. The best test setup is a Mac (or Linux box) as the imagehub and 2 Raspberry Pi Computers with PiCameras running imagenode and sending images at the same time. Actually running the test programs using the docs should highlight things that need fixed in the docs. Open an issue or a pull request for anything you think needs fixed or worded more clearly. Any help with any of that stuff would be greatly appreciated!

**Comment by jeffbass** [comment]
I'm prepping for my PyCon 2020 presentation. Pycon 2020 is moving to an online video & posted slide decks format due to the COVID-19 crisis. I'm going try using an "Open an Issue" format for Questions and Answers for that presentation, in this yin-yang-ranch repository. It should go live in a week or 2. if You could take a look and leave feedback either here, or in one of the new issues, that would be helpful. I'm closing this particular issue for now.
